### PR TITLE
Fix use of Swift 6 language mode

### PR DESCRIPTION
**Pull request by orobio**
Adds a Package@swift-6.0.swift to make sure the package is compiled for the Swift 6 language mode. This fixes the visibility of the new withSpan functions, gated by `#if swift(>=6.0)`.

Not sure if this is the desired solution, but it currently works for us. Let me know if something else is required and I'll be happy to look into it.

Edit:
After digging in some more, I think it would be better to update all `#if swift(>=6.0)` conditionals to `#if compiler(>=6.0)`. Would that be an acceptable solution?

### CODE REVIEW

**Comment by Lukasa** [comment]
I think we should take your suggestion of updating to use `#if compiler`, not `#if swift`.

**Comment by orobio** [comment]
> I think we should take your suggestion of updating to use `#if compiler`, not `#if swift`.

It's updated to use `#if compiler`. I just found a [comment](https://github.com/apple/swift-distributed-tracing/pull/148#discussion_r1704541776) on the previous pull request, regarding the deprecation being done unconditionally. I feel we should have both `@available...` and `@_disfavoredOverload` inside the `#if` blocks. If you agree, I can push an update for that as well.

**Comment by Lukasa** [comment]
Yeah, I'm not wild about the deprecation being present when there is no alternative choice.

**Comment by orobio** [comment]
> Yeah, I'm not wild about the deprecation being present when there is no alternative choice.

I pushed a fix for this as well.

**Comment by Lukasa** [comment]
@ktoso I think we need a review from you here

**Review by slashmo — APPROVED** [review]
LGTM

**Review by ktoso — APPROVED** [review]
These look good, thank you very much!

Definitely agreed on #if guarding the deprecations as well, thank you for doing that

**Comment by ktoso** [comment]
Thanks for the ping! Coming out of sick leave inbox was overwhelmed 😅

**Comment by ktoso** [comment]
@swift-server-bot test this please

**Comment by ktoso** [comment]
docc plugin seems borked on 5.7? Seems weird 🤔 Need to investigate what's up

**Comment by jessezamora** [comment]
Anything new here?

**Comment by orobio** [comment]
Could this have been a temporary glitch? Should we perhaps run the test again?

**Comment by ktoso** [comment]
@swift-server-bot test this please

**Comment by ktoso** [comment]
Sorry I was traveling and only now catching up here, let's see what's up here

**Comment by ktoso** [comment]
@swift-server-bot test this please

**Comment by ktoso** [comment]
Thank you, I'll cut a 1.1.2 with this

**Pull request merged**
