### PR TITLE
Bump minimum Swift version to 5.7

### PR DESCRIPTION
**Pull request by rnro**
Motivation:

Now that Swift 5.9 is GM we should update the supported versions and remove 5.6

Modifications:

* Update `Package.swift`
* Remove guards for swift <5.7
* Add deprecation annotations to `LegacyTracer` API
* Delete the 5.6 docker compose file and make a 5.10 one
* Update docs

Result:

Remove support for Swift 5.6, add 5.10

### CODE REVIEW

**Comment by yim-lee** [comment]
CI updated. @swift-server-bot test this please

**Comment by ktoso** [comment]
Ok all jobs failing here due to warnings as errors etc.

I'll look into addressing this soon

**Review by ktoso — APPROVED** [review]

**Comment by ktoso** [comment]
I'll handle this -- the fallout is the deprecation warnings since we have warnings as errors...

**Comment by ktoso** [comment]
Done, thank you! I'll call a 1.1.0 with this

**Pull request merged**
