### PR TITLE
Updated to use HTTPS for swift-distributed-tracing-baggage

### PR DESCRIPTION
**Pull request by 0xLeif**

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-server-bot test this please

**Comment by ktoso** [comment]
Thanks a lot @0xLeif! The fix was meant to get in earlier but sadly everyone else with review/write rights is asleep and I could not approve my own PR 😅

We need to make the same change in swift-distributed-tracing-baggage, and I'll tag an 0.1.1 of projects so one can ensure to depend on the actually working dependency chain.

**Comment by 0xLeif** [comment]
> Thanks a lot @0xLeif! The fix was meant to get in earlier but sadly everyone else with review/write rights is asleep and I could not approve my own PR 😅
> 
> We need to make the same change in swift-distributed-tracing-baggage, and I'll tag an 0.1.1 of projects so one can ensure to depend on the actually working dependency chain.

I have a PR for swift-distributed-tracing-baggage [here](https://github.com/apple/swift-distributed-tracing-baggage/pull/8)

**Review by ktoso — APPROVED** [review]

**Comment by ktoso** [comment]
@swift-server-bot test this please

**Pull request merged**
